// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tv3a/internal/app/system/dao/internal"
)

// internalPvDao is internal type for wrapping internal DAO implements.
type internalPvDao = *internal.PvDao

// pvDao is the data access object for table pv.
// You can define custom methods on it to extend its functionality as you wish.
type pvDao struct {
	internalPvDao
}

var (
	// Pv is globally public accessible object for table pv operations.
	Pv = pvDao{
		internal.NewPvDao(),
	}
)

// Fill with you ideas below.
