// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Pv is the golang structure for table pv.
type Pv struct {
	Id        int         `json:"id"        description:""`
	Url       string      `json:"url"       description:""`
	Event     string      `json:"event"     description:""`
	Ip        string      `json:"ip"        description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
