# CLI.
gfcli:
  gen:
    dao:
      - link:            ""
        tables:          "sys_role_dept"
        removePrefix:    "gf_"
        descriptionTag:  true
        noModelComment:  true
        path: "./internal/app/system"