apiVersion: extensions/v1
kind: Ingress
metadata:
  name: think-js-pro-go-route
spec:
  rules:
    - host: www.c3340ad5c4bda474e863f94e4629d72f7.cn-zhangjiakou.alicontainer.com
      http:
        paths:
          - backend:
              serviceName: think-js-pro-go-service
              servicePort: 8080
            path: /
