apiVersion: extensions/v1
kind: Ingress
metadata:
  name: think-js-pro-go-route
spec:
  rules:
    - host: www.c5a194a8ee10044eba673c20eb3367692.cn-beijing.alicontainer.com
      http:
        paths:
          - backend:
              serviceName: think-js-pro-go-service
              servicePort: 8080
            path: /
