apiVersion: v1
kind: Service
metadata:
  name: think-js-pro-go-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: think-js-pro-go-sample
  sessionAffinity: None
  type: ClusterIP